name: Deploy main

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test-go:
    name: Go
    uses: ./.github/workflows/go-test.yaml

  cmd:
    name: Go
    uses: ./.github/workflows/cmd.yaml
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    with:
      upload: true
      manifest_file: default.json
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  tf-dev:
    name: tf-dev
    needs: [cmd, test-go, validate]
    concurrency:
      group: dev
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    uses: ./.github/workflows/tf-apply.yaml
    with:
      environment: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}

  ui-dev:
    name: UI (dev)
    needs: [tf-dev]
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    uses: ./.github/workflows/ui.yaml
    with:
      environment: dev
      upload_ui: true
    secrets:
     AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
     WEB_BUCKET: ${{ secrets.WEB_BUCKET }}
