name: PR
on:
  pull_request: { }

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Go
    uses: ./.github/workflows/go-test.yaml

  cmd:
    name: Go
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    uses: ./.github/workflows/cmd.yaml
    with:
      upload: true
      manifest_file: ${{ format('pr{0}.json', github.event.pull_request.number) }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      BINARY_BUCKET: ${{ secrets.BINARY_BUCKET }}

  ui:
    name: UI
    uses: ./.github/workflows/ui.yaml
    permissions:
      contents: read
      id-token: write # OIDC authentication with AWS
    with:
      environment: dev
      upload_ui: false

  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  tf-plan:
    name: Terraform
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    uses: ./.github/workflows/tf-plan.yaml
    with:
      manifest_file: ${{ format('pr{0}.json', github.event.pull_request.number) }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
