name: "sast"

on:
  pull_request: {}
  schedule:
    - cron: '36 9 * * *'

permissions: {}

jobs:
  sast:
    name: sast
    permissions:
      contents: read
    uses: ockendenjo/actions/.github/workflows/sast.yaml@1927116938e4146cc2fb47f52b2126c799c27ef9 # zizmor: ignore[stale-action-refs,ref-version-mismatch]
