name: UI

on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN:
        required: false
      WEB_BUCKET:
        required: false
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      upload_ui:
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  build:
    name: Build
    timeout-minutes: 2
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC authentication with AWS
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'

      - name: Install Node modules
        working-directory: src
        run: npm install

      - name: Check formatting
        working-directory: src
        run: npx prettier --check .

      - name: Check linting
        working-directory: src
        run: npx eslint

      - name: Write build info JS
        shell: bash
        run: |
          COUNT=$(git rev-list --count HEAD)
          echo "Build version is v0.${COUNT}"
          echo "export const gitCount = ${COUNT};" > src/src/app/build.ts

      - name: Build
        working-directory: src
        run: npx ng build --configuration aws-${INPUTS_ENVIRONMENT}
        env:
          INPUTS_ENVIRONMENT: ${{ inputs.environment }}

      - name: Assume role
        if: inputs.upload_ui
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d # v6.2.2
        with:
          aws-region: 'eu-west-1'
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Upload
        if: inputs.upload_ui
        working-directory: src
        run: |
          aws s3 sync dist/snooker/browser/ s3://${INPUTS_BUCKET}
        env:
          INPUTS_BUCKET: ${{ secrets.WEB_BUCKET }}
